In [ ]:
import numpy as np

In [177]:
def read_matrix():
    f = open('test.txt', 'r')
    m = []
    for line in f:
        m.append([float(x) for x in line.split()])
    return m

In [178]:
m = read_matrix()
b = np.array([x[-1:] for x in m])
m = np.array([x[:-1] for x in m])
# mt = m.transpose()
# m = mt.dot(m)
# b = mt.dot(b)

In [179]:
#m = np.matrix(m)
b

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [180]:
#m = np.random.rand(3, 3)
B = np.tril(m)
C = np.triu(m, k=1)
B_inv = np.linalg.inv(B)

eigenvalues = np.linalg.eig(-B_inv.dot(C))[0]
print(eigenvalues)
if not all([abs(x) <= 1 for x in eigenvalues]):
    print("Вы проиграли")

def next(x_k):
    return -B_inv.dot(C).dot(x_k) + B_inv.dot(b)
m

[-0.          0.52713385  0.93634848  0.99721901  0.99995767]


array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [181]:
n = 5
BB = np.zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        BB[i][j] = -m[i][j] / m[i][i] if i != j else 0
B1 = np.tril(BB)
B2 = np.triu(BB)
BB

array([[ 0.        , -0.5       , -0.33333333, -0.25      , -0.2       ],
       [-1.5       ,  0.        , -0.75      , -0.6       , -0.5       ],
       [-1.66666667, -1.25      ,  0.        , -0.83333333, -0.71428571],
       [-1.75      , -1.4       , -1.16666667,  0.        , -0.875     ],
       [-1.8       , -1.5       , -1.28571429, -1.125     ,  0.        ]])

In [183]:
def check(x):
    x = [a[0] for a in x]
    for line in m:
        res = sum([a[0] * a[1] for a in zip(line, x)])
        print(res)

def should_finish(prev, curr, eps=0.0001):
    #return np.linalg.norm(prev - curr) < eps * (1 - np.linalg.norm(BB)) / np.linalg.norm(B2)
    return np.linalg.norm(prev - curr) / np.linalg.norm(curr) < eps

In [185]:
prev = np.array([[0], [0], [0], [0], [0]])
curr = next(prev)
cnt = 1
while not should_finish(prev, curr, eps=0.0000001):
    # print(x)
    prev = curr
    curr = next(curr)
    cnt += 1
print(curr)
print(cnt)
print(check(curr))

[[   124.51271409]
 [ -2871.05498108]
 [ 14451.89106919]
 [-24582.94495357]
 [ 13202.26985579]]
143323
0.9999793737833897
2.0001158974628197
2.9997651616363328
4.000146729097878
5.0000000000009095
None


In [ ]:
prev = np.array([[0], [0], [0], [0], [0]])
curr = next(prev)
cnt = 1
w = 2
while not should_finish(prev, curr, eps=0.0000001):
    # print(x)
    prev = curr
    curr = next(curr)
    curr += (w - 1) * (curr - prev)
    cnt += 1
print(curr)
print(cnt)
print(check(curr))

In [161]:
B1.dot(curr) + B2.dot(curr) + b

array([[3.22030935],
       [0.49416622],
       [2.98369604],
       [3.57453371]])

In [182]:
(1 - np.linalg.norm(BB)) / np.linalg.norm(B2)
np.linalg.norm(BB, ord=1)


6.716666666666667

In [176]:
for i in range(0, 5):
    for j in range(0, 5):
        print(1 / (1.0 + i + j), end=' ')
    print()

1.0 0.5 0.3333333333333333 0.25 0.2 
0.5 0.3333333333333333 0.25 0.2 0.16666666666666666 
0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285 
0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 
0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 
